engines:
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- recipes/*
- log/*
- recources/*
- docs/*