#!/usr/bin/python
#  coding=utf-8

if __name__ == '__main__':
    import os
    import sys
    import logging

    base_path = os.path.dirname(os.path.realpath(__file__))
    sys.path.append(base_path)

    from stackupdater.bin import Cli
    from stackupdater.src.lib import logger
    from stackupdater.src.config import *

    logger_path = "/var/log/stack-updater" if global_log() else os.path.join(base_path, local_log_path())
    print "Logging into {}".format(logger_path)
    logger.init_logger(logging.NOTSET, logger_path)

    cli = Cli(base_path)
    cli.run()