#!/usr/bin/python
#  coding=utf-8

if __name__ == '__main__':
    import os
    import sys
    import logging

    base_path = os.path.dirname(os.path.realpath(__file__))
    sys.path.append(base_path)

    from app import Cli
    from app import logger
    from app.config import *

    logger.init_logger(logging.NOTSET, os.path.join(base_path, log_path()))

    cli = Cli(base_path)
    cli.run()